### ISSUE TITLE
LatticeAoS

### ISSUE THREAD

**Issue by Olllom** [Olllom/lettuce#6]
As discussed before, we might want to do ourselves a pleasure and get rid of the LatticeAoS class (abstracting all the indexing has taken too much effort up to this point and we want to keep the code as simple as possible).

Before making the final decision, Dominik is going to run some benchmarks on the Volta nodes. If the difference in performance turns out to be marginal (or in favor of the structure-of-array Lattice), let's get rid of the thing asap.

TODO (@dominikwilde): Please post the benchmark results here.

**Comment by dominikwilde** [comment]
Here are the results for the 3D Taylor Green Vortex benchmark:

Simulated on the V100 of the H BRS cluster

**All results in MLUPS**
```

Precision: torch.float32 1000 time steps
LatticeAoS with Resolution 16 ^3: 2.2559180646626147
Lattice    with Resolution 16 ^3: 2.5851697616821916
LatticeAoS with Resolution 32 ^3: 12.104913438190378
Lattice    with Resolution 32 ^3: 20.399304757389718
LatticeAoS with Resolution 64 ^3: 16.42895883751184
Lattice    with Resolution 64 ^3: 103.68737285961073
LatticeAoS with Resolution 128 ^3: 16.668502491515284
Lattice    with Resolution 128 ^3: 111.86887113473885
LatticeAoS with Resolution 170 ^3: 15.96431402894369
Lattice    with Resolution 170 ^3: 112.9878616160901
LatticeAoS with Resolution 256 ^3: 15.549368920938692
Lattice    with Resolution 256 ^3: 113.88971342933571

Precision: torch.float64 1000 time steps
LatticeAoS with Resolution 16 ^3: 2.2574557353164653
Lattice    with Resolution 16 ^3: 2.576515041119065
LatticeAoS with Resolution 32 ^3: 9.778973406191161
Lattice    with Resolution 32 ^3: 20.502249990387124
LatticeAoS with Resolution 64 ^3: 13.503848330489335
Lattice    with Resolution 64 ^3: 69.3868001274219
LatticeAoS with Resolution 128 ^3: 13.434663226516776
Lattice    with Resolution 128 ^3: 69.46307419789606
LatticeAoS with Resolution 170 ^3: 13.407799970286328
Lattice    with Resolution 170 ^3: 69.8188926780614
```

[3DTGVbenchmark.py.txt](https://github.com/Olllom/lettuce/files/3675717/3DTGVbenchmark.py.txt)

**Comment by Olllom** [comment]
Holy shit. Let’s bury this thing for sure!

**Comment by Olllom** [comment]
It is kind alarming that the memory layout is so crucial in terms of performance. This makes me think if we have any other parts in the code where changing the layout would give us an order of magnitude speedup 🙈

**Comment by Olllom** [comment]
LatticeAoS removed in #8
